/*
 * The MIT License
 *
 * Copyright 2023 HP.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package mahasiswa.view;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mahasiswa.koneksi.KoneksiDatabase;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import mahasiswa.koneksi.KoneksiDatabase;

/**
 *
 * @author HP
 */
public class FrameCetak extends javax.swing.JFrame {

    /**
     * Creates new form FrameCetak
     */
    public FrameCetak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_alldata = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_datapribadi = new javax.swing.JButton();
        btn_program = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        btn_alldata.setText("PRINT ALL DATA");
        btn_alldata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alldataActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mahasiswa/assets/main.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn_datapribadi.setText("PRINT DATA MAHASISWA");
        btn_datapribadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datapribadiActionPerformed(evt);
            }
        });

        btn_program.setText("DATA PROGRAM MAHASISWA");
        btn_program.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_programActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_alldata, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(btn_datapribadi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_program, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_alldata)
                .addGap(18, 18, 18)
                .addComponent(btn_datapribadi)
                .addGap(18, 18, 18)
                .addComponent(btn_program)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_alldataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alldataActionPerformed
     String reportPath = System.getProperty("user.dir") + "/src/mahasiswa/report/data_calon_mahasiswa/data_calon_mahasiswa.jasper";

    try {
        // Menggunakan koneksi dari kelas KoneksiDatabase
        KoneksiDatabase koneksiDB = new KoneksiDatabase();
        java.sql.Connection conn = null;
        try {
            conn = koneksiDB.koneksi();
        } catch (SQLException ex) {
            Logger.getLogger(FrameCetak.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Parameter laporan (jika diperlukan)
        HashMap<String, Object> parameters = new HashMap<>();

        // Mengisi laporan menggunakan JasperFillManager
        JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, conn);

        // Menampilkan laporan menggunakan JasperViewer
        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setVisible(true);
    } catch (JRException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(
            null,
            "Terjadi kesalahan: " + ex.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btn_alldataActionPerformed

    private void btn_datapribadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datapribadiActionPerformed
        String reportPath = System.getProperty("user.dir") + "/src/mahasiswa/report/data_pribadi/data_pribadi.jasper";

    try {
        // Menggunakan koneksi dari kelas KoneksiDatabase
        KoneksiDatabase koneksiDB = new KoneksiDatabase();
        java.sql.Connection conn = null;
        try {
            conn = koneksiDB.koneksi();
        } catch (SQLException ex) {
            Logger.getLogger(FrameCetak.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Parameter laporan (jika diperlukan)
        HashMap<String, Object> parameters = new HashMap<>();

        // Mengisi laporan menggunakan JasperFillManager
        JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, conn);

        // Menampilkan laporan menggunakan JasperViewer
        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setVisible(true);
    } catch (JRException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(
            null,
            "Terjadi kesalahan: " + ex.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btn_datapribadiActionPerformed

    private void btn_programActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_programActionPerformed
       String reportPath = System.getProperty("user.dir") + "/src/mahasiswa/report/program/program.jasper";

    try {
        // Menggunakan koneksi dari kelas KoneksiDatabase
        KoneksiDatabase koneksiDB = new KoneksiDatabase();
        java.sql.Connection conn = null;
        try {
            conn = koneksiDB.koneksi();
        } catch (SQLException ex) {
            Logger.getLogger(FrameCetak.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Parameter laporan (jika diperlukan)
        HashMap<String, Object> parameters = new HashMap<>();

        // Mengisi laporan menggunakan JasperFillManager
        JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, conn);

        // Menampilkan laporan menggunakan JasperViewer
        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setVisible(true);
    } catch (JRException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(
            null,
            "Terjadi kesalahan: " + ex.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btn_programActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alldata;
    private javax.swing.JButton btn_datapribadi;
    private javax.swing.JButton btn_program;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
